### ISSUE TITLE
Update wording on self-report frame and feedback frame

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#109]
Self report: First question needs rewording to keep the question wording constant pre and post activity; e.g. "Which emotion(s) are you feeling right now after thinking about the Reference Event?" -> "Which emotion(s) are you feeling right now *in relation to* the Reference Event?

Post survey: we should make it explicit that we are asking the same questions again (we'd like to ask the same questions after completing the activity); might feel like a mistake other wise.

"Which features did you like the most/least?" It is unclear what is meant by "feature" the app feels like it's just one thing. ---> don't use the word "features"

**Comment by mayacakmak** [comment]
Made the wording change "in relation to" in the self report frame.

Added warning in the post-app transition frame that the participant will be asked to "repeat" the scales they responded to before using the app, so they don't think it is a mistake.

Removed the word "feature" -- this undoes changes made in Issue #99 but I think removing the term makes sense.
