### ISSUE TITLE
Update feedback survey

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#111]
* Feedback: Yes/no question "Did the app help you figure out your emotion(s)?" Should be a rating scale, either 'to what extent..' Or stating agreement with statements like "the app helped me figure out my emotions".

**Comment by mayacakmak** [comment]
Converted the feedback questions to Likert scale agreement with statements and added the instruction 'state your agreement' to those from frames. 

Also added more statements on Page 1 to get to more nuanced influences of the app, current list: 
- The app helped me better understand my emotion(s).
- The app made me realize I had certain emotions that I did not realize before.
- The app made me more certain about the emotions I thought I have.
- The app helped me understand why I had certain emotions.
- The app helped me understand the link between my emotions and my thoughts and actions.
