### ISSUE TITLE
Navigation clarity (the next issue)

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#112]
Be clear when you can't go back after clicking "next"
* one idea: the button text is "next (can't go back after clicking this button)"
   * this is very clear but not concise. Can we come up with a still clear but more concise option?

Only block the "back" action when absolutely necessary
* consider allowing in more places.

**Comment by mayacakmak** [comment]
One idea is to change the non-reversable "Next" buttons to "Done" and "Submit" as appropriate. Not as explicit as option one above but more concise.

**Comment by mayacakmak** [comment]
I went ahead and implemented the simple indicators "OK" (if only statements) "submit" (if there are questions) or "done" (within the app) to replace "next" for non-reversible forward navigation buttons. is_next_reversible() was already implemented so this just required a simple check within the render() function of Nav, but had to add a has_questions flag to frames to have the more meaningful keywords for the buttons.
