### ISSUE TITLE
update ListBodyFrame to support get_user_input()

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#26]
== Example of view data structure for user input== 
‘statements’ lists all answer choices that will be rendered on frame (from sample_app.js).
‘answers’ is what will be created by the view of each frame (subclass) that will display user input. False implies user did not check this box.
```
'statements': [  // passed in to the frame's constructor
                'its purr',
                'its floof',
                'its bark',
],
'answers' : {   // returned by the frame's get_user_input() method
                'its purr': false,
                'its floof': false,
                'its bark': false,
},
```

**Comment by sittr7** [comment]
This code specifies the format of what get_user_input needs to return. 

https://github.com/lrperlmu/emotional_clarity/blob/c157ddeb15a55f208ffd1fa573296387a3155c27/appside/model/dbt_worksheet_model.js#L225-L226

**Comment by sittr7** [comment]
Made code changes in #48. Closing.
