### ISSUE TITLE
Data source for DERS questions

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#56]
Make a file with a json object with the data for momentary DERS.
- Statement text
- "F" or "R" for forward or reverse

Example
{
["I know the current source of my emotions", "F"],
...,
}

**Comment by lrperlmu** [comment]
`data/momentary_ders.js`
* when those frames get constructed, that's where the data comes from

**Comment by sittr7** [comment]
no operations needed :)
