### ISSUE TITLE
filter out positive emotions

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#85]

**Comment by mayacakmak** [comment]
Moved positive emotions into a separate file, cna be loaded separately and merged if needed. This is a quick fix that covers the scenarios we have in mind in the near future but we might want to implement a filter function, probably called in the constructor of DbtWorksheetModelFwd to include/exclude specific emotions from the knowledgebase. 

Also not sure where the implementation is for the "backwards" variants of the apps which also require a filtering functionality based on user's indicated emotions, so perhaps that can be reused here.

**Comment by lrperlmu** [comment]
there's no implementation for backwards variants yet, but good idea on reusing code for it.
