### ISSUE TITLE
post mood check

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#92]
Collect the answers to the following questions on a 5 point likert scale

How distressed are you right now? 
How sad are you right now?

Likert scale should have the following labels:

Very slightly or not at all 
A little 
Moderately 
Quite a bit 
Extremely

This goes after the survey about app effectiveness and before the end frame.

**Comment by lrperlmu** [comment]
Steps for adding a new frame. Let me know if I can help in any other way.

(Optional) Create the new frame class
* Many new frame types can now be implemented with an instance of FormFrame
* Location: appside/frames/[frame name].js
* Needs the following methods:
  - constructor
    - pass in data to create the frame
  - render 
    - create the html elements of the frame and replace the current <div id="frame">
  - get_user_input
    - collect any user input from the html fields specified in render() and return them as a Map
    - the map will be consumed by DBTWorksheetModelFwd.update, which stores the data into a UserDataSet object called this.uds


Strings and other constants
* Location: appside/frames/constants.js
* All strings (such as user-facing text) and magic numbers belong in this file


(Optional) Unit test for the html rendering
* This is for testing the html rendering of a frame before it is incorporated into the model
* appside/data/sample_app.js
  - create a mock-up of the frame data here with sample strings to be fed into the frame constructor
* appside/test_frames.js
  - add an entry to test_methods
  - implement a test method to render it
* appside/test_frames.html
  - import the new frame file as a script if applicable
* To run
  - navigate in browser to .../appside/test_frames.html?frame=frame_name
  - in the URL above, replace "frame_name" with the proper string


Incorporate into the model
* Location: appside/model/dbt_worksheet_model.js
* Configuration (in class DbtWorksheetModelConfig)
  - Note: This is configurable so we can easily toggle between showing just the app or app+study
  - Add documentation for which configuration setting will toggle the existence of the new frame
  - OR add a new config setting to toggle its existence
* Helper method to build the frame (in class DbtWorksheetModelFwd)
  - get data from constants.js and call the frame's constructor
  - UserData items associated with the frame should be constructed and added to this.uds
* Call build method in constructor of DbtWorksheetModelFwd
  - check whether the designated config flag is toggled on
  - call the helper method to build the frame
  - push it into this.frames


Integration Test
* appside/model/test_dbt_worksheet_model.js
  - add an entry to test_methods
  - implement a new test method
* appside/test_model.html
  - import the new frame file as a script if applicable
* To run:
  - navigate in browser to .../appside/test_model.html?test=summary&variant=bio
  - in the URL above, replace "summary" with the proper string

**Comment by lrperlmu** [comment]
Here's a pull request from Rachel adding the Consent frame: #66 
It's a pretty good example of the things you need to do for the post mood check frame -- I referenced it when I was writing the instructions above.

**Comment by mayacakmak** [comment]
Implemented this using LikertFrame, i.e. without creating a new frame type.

**Comment by mayacakmak** [comment]
The submitted mood check document on Zipline seems to have more questions than the ones indicated above (with same qualifiers):

- How distressed are you right now?
- How upset are you right now?
- How nervous are you right now? 
- How sad are you right now?

Was there a discussion with the IRB reviewers that only the two above would be sufficient? Looks like the mood check follow up with positive mood induction depends only on the two questions, so that might have been a reason, but adding all four questions for now.

**Comment by lrperlmu** [comment]
I discussed this with Kevin earlier. The mood check doc on zipline also says:

> For those reporting >3 on either the distress and sadness variables, the system will automatically guide them through  the following prompts

We decided to eliminate the other questions since those responses are not used for anything. Do you think it's necessary to submit an IRB modification for this? I was leaning towards not, since they approved the mood check which says only those two questions will be checked.
