### ISSUE TITLE
update post survey

### ISSUE THREAD

**Issue by lrperlmu** [lrperlmu/emotional_clarity#99]
Which features did you like most?
--> Which features did you like? Name as many as you can think of.

ditto for features disliked.

**Comment by mayacakmak** [comment]
I was just thinking about doing this while working on issue #111 

Updated wording of questions as:
- Which features of the app did you like? Name as many as you can think of.
- Which features of the app did you dislike? Name as many as you can think of.

**Comment by mayacakmak** [comment]
Issue #109 undoes this change because it seems more important to address (removing of the term 'feature' which might be confiusing). Now the questions simply say:
- What did you like about the app?
- What did you dislike about the app?
